### PR TITLE
fix: exclude `.svelte-kit/` from format checks

### PR DESCRIPTION
**Pull request by BastiDood**
This PR fixes the issues raised in https://github.com/up-csi/up-csi.github.io/pull/83#discussion_r1783713489. Previously, when this project was originally built with a bespoke [Parcel](https://parceljs.org/) pipeline, the `.prettierignore` correctly omitted the `.parcel-cache/` folder. However, ever since migrating to SvelteKit + Vite, I forgot to replace that entry in the `.prettierignore` file with `.svelte-kit/`. That means all this time, we've been formatting more files than necessary. 😅

To ensure that the bug was not due to outdated dependencies, I have also bumped the minor versions of all dependencies with the `pnpm up` command.

> [!NOTE]
> If the issue persists for a different unrelated directory, simply add an entry to the `.prettierignore` file. If applicable, also do this for the `eslint.config.js` file.

### CODE REVIEW

**Comment by VeeIsForVanana** [comment]
Thanks @BastiDood ! I'll issue the approval, but what I'm wondering at this point is why was it a non-issue for Ehren and me, where it only triggered one file?

**Review by VeeIsForVanana — APPROVED** [review]

**Comment by BastiDood** [comment]
That I'm not too sure about without seeing the logs. I'd like to know which files were specifically flagged.

**Comment by VeeIsForVanana** [comment]
Here are some incomplete logs from @Ulyzses when he ran into the problem. For reference, he had only edited one file, `src/routes/+page.svelte`

Untitled
Untitled

**Comment by conventoangelo** [comment]
I tried @BastiDood's fix by changing the `.prettierignore` file. I still encounter the same issue when running `pnpm fmt`. I don't think it's related to the `.svelte-kit` folder.

P.S. Sorry for the light mode screenshot.

image

**Comment by ehrelevant** [comment]
Hmm, I think it would also help to see a `git diff` after applying `pnpm fmt:fix`. 

Also, noticed both @conventoangelo and @Ulyzses are working on Windows filesystems, while I was testing on Debian. Is there a chance it might be related to some strange quirk of cloning to a Windows filesystem that we're not very aware of (maybe related to CRLF/LF)?  

Though, if this were the case, I feel like this should have happened a long time ago.

**Comment by conventoangelo** [comment]
This is what is being returned by `git diff` on my end.

`warning: in the working copy of '.github/workflows/deploy.yml', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.linthtmlrc.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.prettierrc.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.stylelintrc.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'COPYING.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'eslint.config.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/app.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/hooks.server.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/assert.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/components/Button.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/components/CartoonCard.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/components/Contact.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/components/ContentContainer.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/components/EventCard.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/components/EventsPanel.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/components/HeroComponent.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/fonts/DMSans/font.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/fonts/Inter/font.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/lib/stores/color-scheme.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/+error.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/+layout.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/+page.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/Footer.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/WhoWeAre.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/about/+page.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/about/Card.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/about/MissionVision.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/about/SectionHeaderTextContainer.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/app.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/events/+page.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/events/FeaturedEvent.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/events/events.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/people/+page.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/people/Exec.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/people/TeamCard.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/people/TeamPanel.svelte', LF will be replaced by CRLF the next time Git touches it       
warning: in the working copy of 'src/routes/people/team.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/projects/+page.svelte', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/routes/projects/projects.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'svelte.config.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tsconfig.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'vite.config.js', LF will be replaced by CRLF the next time Git touches it`

**Comment by ehrelevant** [comment]
Okay, guess that confirms it. Really surprised it is related to `CRLF`/`LF`. Did the website teams in the previous sems all use WSL2/Linux by sheer coincidence... 

My guess is Git on Windows converts all `LF` to `CRLF` when cloning/pulling and vice versa when pushing(?). [Prettier then formats this to `LF` by default](https://prettier.io/docs/en/options.html#end-of-line). Now, if you try `git add`ing them, I'm guessing Git will automatically change all the `LF` from Prettier back to `CRLF`. So, in the end, my theory is that only the files that actually had changes unrelated to the `CRLF`/`LF` would end up being committed if you tried. 

Anyhow, I'm not exactly sure if this issue can be solved easily or needs to even be solved at all. Though, this is definitely a mess to think through.

**Comment by conventoangelo** [comment]
It indeed is a Windows Git installation problem. As per @BastiDood's suggestion, I run `git config --global core.autocrlf false` on  my terminal and did not encounter the issue again.

**Comment by VeeIsForVanana** [comment]
@ehrelevant I think what we should do is enforce this as an internal Engineering standard. It would be something we could issue as an RFC for too. Something like "Internal Git Standards".

**Comment by ehrelevant** [comment]
Yep, that sounds good. It should probably also include all our other guidelines regarding conventional commits and linting/formatting.

**Pull request merged**
